import 'package:flutter/material.dart';

//gonna make a bunch of dictionaries of the games of dictionaries that will show
//first and easiest game
Map exagerateMap = {"I have a lot of work to do":["I have so much work to do, it feels like I'm trying to move a mountain with a teaspoon"],"It's a warm day":["It's so warm outside that the pavement is melting into a river of lava"],
                          "I'm feeling a bit tired":["I'm so tired that if I lie down, I might hibernate until next year"],"My backpack is heavy":["My back pack is so heavy that it's like carrying a ton of bricks on my shoulders"],
                          "I'm hungry":["I'm so hungry that I could devour an entire pizza, plus a mountain of ice cream for dessert"],"There's a lot of traffic today":["There's so much traffic that it's as if the entire world decided to have a parade on this road"],
                          "This line is long":["The line is so long that I think I'll have time to write a novel before reaching the front"],"It's raining lightly":["It's raining so heavily that it's as if the sky opened up and dumped an ocean on us"],
                          "I have a few missed calls":["I have so many missed calls that my phone might as well be a hotline for the entire planet"],"I have some things to carry":["I have so many things to carry that it's like I'm lugging around a circus tent and elephant"],
                          "I need a break":["I need a break so desperately that it's as if I've been running a marathon on the sun"],"The queue is moving slowly":["The queue is moving so slowly that a sloth on a leisurely stroll would beat us to the finish line"],
                          "I have a few emails to answer":["I have so many emails to answer that it's like trying to swim through an ocean of messages"],"The coffee is strong":["The coffee is so strong that it could wake the dead and grant them superpowers"],
                          "My phone battery is low":["My phone battery is so low that it's on life support and clinging to existence"],"The room is dark":["The room is so dark that it feels like a black hole in here, swallowing all the light."],
                          "I'm running late":["I'm running so late that I'll be arriving at the speed of a snail with a broken leg"],"I'm a bit stressed":["I'm so stressed that it's as if I'm juggling a dozen chainsaws while tightrope-walking over a volcano"],
                          "The music is loud":["I have so many errands to run that it's like I've become the personal assistant for the entire town"],"I need to clean my room":["I need to clean my room so badly that it resembles a post-apocalyptic wasteland"],
                          "I'm a little stressed about the test":["I'm so stressed about the test that I feel like I'm preparing for a cosmic battle against an army of exam demons"],"I have a few notifications on my phone":["I have so many notifications on my phone that it's like a digital fireworks display that never ends"],
                          "The traffic is congested":["The traffic is so congested that it's like a parking lot for time travelers from the 22nd century"],"I've got a small problem":["I've got such a colossal problem that it's like dealing with an erupting volcano in my backyard"],
                          "The room is a little chilly":["The room is so chilly that it's like I've been transported to the frozen tundra of Antarctica"]
};

Map detailPaintMap = {"Being Tired":["I'm feeling like a zombie","I could sleep for a year","I'm running on fumes"],
                                    "Something Exciting":["This is a real adrenaline-pumper","it's a heart-thumping experience","I can't sit still with all this excitement"],
                                    "A difficult Task":["It's like trying to move a mountain","This is a brain-buster","It's as tough as nails"],
                                    "Delicious Food":["This dish is a taste explosion","It's a lavor party in my mouth","I could eat this until the cows come home"],
                                    "Beautiful Scenery":["The view is a feast for the eyes","It's like a postcard come to life","Nature has painted a masterpiece her"],
                                    "A loud noise":["It's as noisy as a rock concert","The racket is deafening","I can't hear myself think over this cacophony"],
                                    "Someone Intelligent":["They're a walking enyclopedia","Their IQ is off the charts","They have a mind like a steel trap"],
                                    "Feeling Grateful":["I'm as thankful as a turkey on thanksgiving","My heart is overflowing with gratitude"],
                                    "Feeling Nervous":["I've got the butterflies in my stomach","My heart is doing somersaults","I'm as jumpy as a cat on a hot tin roof"],
                                    "Something Beautiful":["It's a sight for sore eyes","This is pure eye candy","It's like a work of art"],
                                    "A busy place": ["It's a beehive of activity","This place is busting like a marketplace","It's as crowded as a can of sardines"],
                                    "Someone Talkative":["They have a gift of gab","They could talk the hind legs off a donkey","Their mounth is like a runaway train","Their mouth is like a motor that won't shut off"],
                                    "Unpleasant Odor":["It smells like something the cat dragged in","The stench is enough to knock you off your feet","It's as foul as a gym locker room"],
                                    "Feeling Confused":["I'm as lost as a need in a haystack","My mind is a tangeld web","I'm in a state of total bewilderment"],
                                    "A small Amount":["It's just a drop in the bucket","It's a mere speck in the grand scheme of things","It's as small as a grain of sand"],
                                    "Feeling Energetic":["I've got energy to burn","I'm as lively as a spring lamb","My batteries are fully charged"],
                                    "Feeling Happy":["I'm on cloud nine","I've got a smile from ear to ear","It feels like I've won the lottery"],
                                    "A quiet place":["It's as peaceful as a monastery","You could hear a pin drop","It's so tranquil, you can almost hear the silence"],
                                    "Someone Stylish":["They have a flair for fashion","They're as sharp as a tack", "They're a true fashionista"],
                                    "Unpredictable weather":["The weather is as changeable as a chameleon","It's like a box of chocolates; you never know what you'll get","It's as fickle as a cat's mood"],
                                    "Feeling Anxious":["I'm as twitch as a long-tailed cat in a room full of rocking chairs","My nerves are on edge","I've got a case of the jitters"],
                                    "A vivid Dream":["It was like a movie playing in my head","My dream was as clear as crystal","It felt like I was living in a different world"],
                                    "A strong Scent":["The aroma is as potent as a perfume store","It's so fragrant it's like being in a flower garden","The scent is overpowering"],
                                    "Feeling Relaxed":["I'm as calm as a summer's day","I'm as laid-back as a hammock on a lazy Sunday","I'm in a state of serene tranquility"],
                                    "Something Chaotic":["It's like a tornado hit this place","It's a complete madhouse","Chaos reigns supreme"],
                                    "Beautiful Sunset":["The sky is ablaze with colors","It's a painting come to life","The sunset is a breathtaking masterpiece"],
                                    "A Croweded Space":["It's packed like a sardines can","There's barely room to breathe","You can't swing a cat in her"],
                                    "Feeling Courageous":["I'm as brave as a lion","I've got the heart of a warrior","Fear has no place in my heart"],
                                    "Unusual or Unique":["This is one of a kind","It's as rare as a blue moon","There's nothing quite like it in the world"],
                                    "Feeling Grumpy":["I woke up on the wrong side of the bed","I'm in a foul mood","I'm as crabby as a bear with a thorn in its paw"]
};

Map metaphorMap= {"I wanted to soar like an eagle, but____":["but I ended up flopping like a fish out of the water","I fluttered like a feather in the wind","I stumbled like a baby bird learning to fly","I glided more like a papre airplane","I flapped like a chicken trying to take flight","I nose dived like a stone in the water"],
                                    "I thought I'd uncover buried treasure, but____":["all I found was a can of worms","I found a box of old socks instead","I stumbeled upon my childhood diary","it turned out to be a stash of expired coupons","I discovered a collection of mismatched buttons","I unearthed a nest of ants","I dug up a rusty bicycle frame","I ended up with a jar of marbles"],
                                    "I aimed to be as fast as a cheetah, but____":["I moved more like a sloth on a lazy Sunday","I moved more like a snail with a backpack","my speed was more tortoise than a hare","I was as fleet-footed as a sloth on a coffee break","I was like a turle racing through peanut butter","I moved at a glacial pace"],
                                    "I was hoping to have the grace of a swan, but____":
                                    ["I stumbled around like a drunken penguin""I ended up looking more like a clumsy goose","I moved as elegantly as a bull in a china shop.",
                                    "I danced around like a marionette with tangled strings.",
                                    "I stumbled and tripped like a toddler learning to walk.",
                                    "I glided as gracefully as a brick falling from a tree.",
                                    "I wobbled like a Jenga tower on the brink of collapse.",
                                    "I was as poised as a shopping cart with a wonky wheel."],
                                    "I tried to solve the puzzle like Sherlock Holmes, but____":
                                    ["I stumbled around like a detective in a Scooby-Doo episode","I ended up as clueless as Inspector Clouseau.",
                                    "I felt more like a contestant on a game show than a detective.",
                                    "I made deductions that were as accurate as a broken clock.",
                                    "I had as many false leads as a GPS with a glitch.",
                                    "I turned a simple case into a convoluted mystery.",
                                    "I was about as perceptive as a brick wall.",
                                    "I was more Watson than Holmes in my deductions.",
                                    "I realized I'm better at creating puzzles than solving them."],
                                    "I wanted my speech to be as smooth as jazz, but____":
                                    ["it turned out more like a record skipping","I stumbled over my words like a toddler learning to walk.",
                                    "It came out more like a broken record, repeating the same thing over and over.",
                                    "I sounded like a cat trying to sing opera.",
                                    "It ended up like a car with a sputtering engine.",
                                    "I rambled on like a GPS that couldn't find its way.",
                                    "It turned into a jumbled mess, like a crossword puzzle with the wrong answers.",
                                    "I lost my train of thought like a conductor in a maze of tracks.",
                                    "I sounded as smooth as a gravel road in a thunderstorm."],
                                    "I aimed to have patience of a saint, but____":
                                    ["I lost it faster than a kid in a candy store","I lost it quicker than a balloon at a porcupine convention.",
                                    "It evaporated faster than ice cream on a scorching summer day.",
                                    "It vanished like socks in a washing machine.",
                                    "It slipped through my fingers like water through a sieve.",
                                    "It was as fleeting as a shooting star."],
                                    "I thought I'd make entrance like a movie star, but____":
                                    ["I tripped in like a slapstick comedian",
                                    "I stumbled in like a klutzy extra.",
                                    "I walked in like a lost tourist.",
                                    "I waltzed in like a daydreaming dancer.",
                                    "I floated in like a wayward balloon.",
                                    "I swaggered in like a cowboy who lost his hat.",
                                    "I shuffled in like a retiree headed to the bingo hall.",
                                    "I pranced in like a catwalk model on a tightrope.",
                                    "I slipped in like a secret agent on a banana peel."],
                                    "I was trying to light up the room, but____":
                                    ["I ended up dimmer than a broken flashlight.","I ended up as effective as a glow-in-the-dark sticker.",
                                    "I couldn't even brighten a closet.",
                                    "I was as illuminating as a burned-out lightbulb.",
                                    "I cast about as much light as a firefly in a stadium.",
                                    "I was about as radiant as a lump of coal.",
                                    "I was as luminous as a rainy day.",
                                    "I was about as helpful as a flashlight with dead batteries.",
                                    "I couldn't even outshine a nightlight."],
                                    "I aimed to be as smooth as silk, but____":
                                    ["I felt more like sandpaper","leaving a trail of splinters in my wake.",
                                    "and people were avoiding me like a rough road.",
                                    "and my attempts at charm grated on everyone.",
                                    "causing friction in every interaction.",
                                    "scratching the surface of diplomacy."],
                                    "I thought I'd make a grand entrance, but____":
                                    ["I tiptoed in like a ninja on a stealth mission",
                                    "I tip-toed in like a mouse in a library.",
                                    "I shuffled in like a reluctant zombie.",
                                    "I crept in like a secret agent.",
                                    "I slid in like a penguin on an icy hill."],
                                    "I wanted to be as sharp as a tack, but____":
                                    ["my wit felt more like a butter knife",
                                    "my brain was in hibernation.",
                                    "my mind was as dull as dishwater.","I was as blunt as a sledgehammer","my thoughts were like a tangled ball of yarn","my wit was on vacation","I felt like a rusty nail in a toolbox","my mind was as clear as mud"],
                                    "I tried to blend in like a chameleon, but____":
                                    ["I stuck out like a sore thumb","I felt like a zebra in a room full of leopards.",
                                    "I was as conspicuous as a neon sign in the dark.",
                                    "I was more like a penguin at a flamingo convention.",
                                    "I was the odd one out", "like a polar bear in the jungle."],
                                    "I thought I'd hit the bullseye, but____":
                                    ["I was miles away from the target, like a dart thrown by a toddler","my arrow landed in the parking lot.",
                                    "I struck the dartboard instead.",
                                    "my aim was more off than a broken compass.",
                                    "I ended up on a completely different target.",
                                    "my accuracy was as elusive as a mirage."],
                                    "I aimed to be as cool as a cucumber, but____":
                                    ["I ended up as flustered as a turkey on Thanksgiving","I turned into a sweating waterfall.",
                                    "I panicked like a cat at a dog show.",
                                    "I was as flustered as a squirrel in traffic.",
                                    "I was as composed as a tornado in a trailer park.",
                                    "I felt as calm as a bull in a china shop."],
                                    "I was hoping to be as strong as an ox, but____":
                                    ["I was as weak as a wet paper bag","I felt as feeble as a kitten.",
                                    "I was as fragile as glass.",
                                    "I was weaker than a wet noodle.",
                                    "I was about as robust as a dandelion."],
                                    "I was trying to be as precise as a surgeon, but____":
                                    ["I ended up as clumsy as a bull in a china shop",    "I ended up sewing buttons on a shirt with dental floss.",
                                    "I performed surgery with a butter knife.",
                                    "I operated with my eyes closed.",
                                    "I left a trail of destruction in the operating room."],
                                    "I aimed to be as sweet as honey, but____":
                                    ["I came across more like a jar of hot sauce","I ended up as sour as a lemon.",
                                    "I came across as bitter as black coffee.",
                                    "I turned out to be as spicy as hot sauce.",
                                    "I sounded as sharp as a vinegar.",
                                    "My words stung like a bee."],
                                    "I wanted to be as confident as a lion, but____":
                                    ["I felt more like a scaredy-cat","I ended up as timid as a mouse.",
                                    "I was as nervous as a long-tailed cat in a room full of rocking chairs.",
                                    "I felt more like a wildebeest surrounded by hungry lions.",
                                    "I roared as loudly as a kitten.",
                                    "I was as hesitant as a squirrel at a busy intersection."],
                                    "I thought I'd be as organized as a librarian, but____":
                                    ["my desk looked like a tornado hit it","my files were more jumbled than a box of tangled Christmas lights.",
                                    "my notes looked like they'd been through a paper shredder.",
                                    "my schedule resembled a chaotic game of Tetris."],
                                    "I tried to be as strong as a rock, but____":
                                    ["I crumbled like a cookie","I shattered like glass.",
                                    "I caved like a sandcastle.",
                                    "I fell apart like a poorly-built puzzle.",
                                    "I crumbled like a sand dune.",
                                    "I broke like a twig."],
                                    "I wanted to navigate through the problem like a GPS, but____":
                                    ["I got lost in a maze of confusion","I took a wrong turn at Albuquerque.",
                                    "my map was upside down.",
                                    "I ended up in Narnia instead.",
                                    "I crashed into a dead end."],
                                    "I aimed to be as stealthy as a ninja, but____":
                                    ["I tripped over my own shoelaces","I tripped over my own shadow.",
                                    "I clanged the pots and pans like a one-man band.",
                                    "I creaked like an old haunted house.",
                                    "I sounded like a herd of elephants tap-dancing.",
                                    "I left a trail of breadcrumbs like Hansel and Gretel."],
                                    "I was hopeing to be as smooth as a pickup line, but____":
                                    ["I was as awkard as a penguin on roller skates","I ended up as awkward as a penguin in tap shoes.",
                                    "my words came out as jumbled as a bag of Scrabble tiles.",
                                    "I fumbled my way through the conversation like a quarterback with butterfingers."]
};

Map  stickLabelMap = {"Vehicle Description": ["We drive a soccer mom's dream van."],
                        "Personality Description": ["I'm a total tech geek, computer wizard."],
                        "Home Description": ["My place is like a cozy log cabin."],
                        "Favorite Food Description": ["My favorite dish is the classic comfort food, mac 'n' cheese."],
                        "Hobbies Description": ["My hobbies are like a whirlwind of adventure and adrenaline."],
                        "Job Description": ["I work in the concrete jungle as a number-crunching spreadsheet warrior."],
                        "Morning Routine Description": ["My morning routine is as chaotic as a circus juggling act."],
                        "Friend Description": ["My friends are a bunch of movie buffs and popcorn connoisseurs."],
                        "Weekend Description": ["My weekends are like a Netflix marathon of relaxation."],
                        "Style of Dressing Description": ["My style is as colorful as a peacock's tail."],
                        "Travel Destination Description": ["I'm heading to a tropical paradise, a beach bum's heaven."],
                        "Favorite Book Description": ["My favorite book is an epic fantasy, a doorstopper of a read."],
                        "Music Genre Description": ["I'm all about classic rock, a time-traveling air guitarist."],
                        "Pet Description": ["My pet is a furry tornado, a living, breathing furball."],
                        "Coffee Order Description": ["My coffee order is like a sugar overdose, a caramel macchiato with extra whipped cream."],
                        "Holiday Celebration Description": ["Our holiday celebration is a family comedy show, a chaotic mix of laughter and chaos."],
                        "Cooking Style Description": ["My cooking style is like a mad scientist, an experiment in every dish."],
                        "Fitness Routine Description": ["My fitness routine is a workout warrior's dream, a daily sweat-soaked boot camp."],
                        "Dream Job Description": ["My dream job is a creative playground, a lifelong imagination expedition."],
                        "TV Show Description": ["My favorite TV show is like a binge-watcher's paradise, a gripping suspense rollercoaster."],
                        "Favorite Movie Description": ["My favorite movie is an emotional rollercoaster, a tearjerker with a happy ending."],
                        "Vacation Spot Description": ["My ideal vacation spot is a postcard paradise, a tranquil beach with crystal-clear waters."],
                        "Social Media Habits Description": ["My social media habits are like a digital nomad, a constant journey through posts and stories."],
                        "Personality Trait Description": ["One of my personality traits is like a ray of sunshine, a perpetual optimist."],
                        "Gardening Style Description": ["My gardening style is a green thumb's fantasy, a jungle of blooms and vegetables."],
                        "Morning Beverage Description": ["My morning beverage is like a hug in a mug, a warm and comforting cup of coffee."],
                        "Neighborhood Description": ["My neighborhood is like a small-town movie set, a close-knit community with a touch of nostalgia."],
                        "Computer Usage Description": ["My computer usage is like a digital wizard, a multitasking maestro with a thousand tabs open."],
                        "Vacation Activity Description": ["My favorite vacation activity is like a kid in a candy store, an adventure seeker exploring new places."],
                        "Art Style Description": ["My art style is like a colorful dream, a canvas filled with vibrant, abstract expressions."]
};
